apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelf-analytics-scraper
  namespace: default
  labels:
    app: shelf-analytics-scraper
spec:
  template:
    metadata:
      labels:
        app: shelf-analytics-scraper
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      volumes:
        - name: google-cloud-key
          secret:
            secretName: service-account-key
      containers:
        - env:
            - name: CLOUD_TRACE_ENABLED
              value: "true"
            - name: PANPRICES_ENVIRONMENT
              value: production
            - name: SHELF_ANALYTICS_PERSIST_NEW_URLS_TOPIC
              value: trigger_shelf_analytics_persist_new_urls
            - name: SHELF_ANALYTICS_UPDATE_PRODUCTS_TOPIC
              value: trigger_shelf_analytics_update_products
            - name: SHELF_ANALYTICS_UPDATE_POPULARITY_TOPIC
              value: trigger_shelf_analytics_update_products_popularity
            - name: CRAWLEE_AVAILABLE_MEMORY_RATIO
              value: "1"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          image: gcr.io/panprices/test-crawlee
          name: shelf-analytics-scraper
          ports:
            - containerPort: 8080
              name: http1
          resources:
            requests:
              cpu: 4000m
              memory: 8Gi
              ephemeral-storage: 4Gi
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
      serviceAccountName: crawlee-scraper
  selector:
    matchLabels:
      app: shelf-analytics-scraper
