apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shelf-analytics-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shelf-analytics-scraper
  minReplicas: 1
  maxReplicas: 200
  targetCPUUtilizationPercentage: 50
