apiVersion: v1
kind: Service
metadata:
  name: shelf-analytics-scraper-service
  namespace: default
  labels:
    app: shelf-analytics-scraper
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: shelf-analytics-scraper
